/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AuthDecor: typeof import('./src/components/AuthDecor.vue')['default']
    CareerPathDialog: typeof import('./src/components/mcp/CareerPathDialog.vue')['default']
    ChatInputBar: typeof import('./src/components/chat/ChatInputBar.vue')['default']
    ChatMessageList: typeof import('./src/components/chat/ChatMessageList.vue')['default']
    DashboardPanel: typeof import('./src/components/DashboardPanel.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExamPlanDialog: typeof import('./src/components/mcp/ExamPlanDialog.vue')['default']
    HomeAppCards: typeof import('./src/components/home/HomeAppCards.vue')['default']
    HomeWeeklyOverview: typeof import('./src/components/home/HomeWeeklyOverview.vue')['default']
    InterviewTalkDialog: typeof import('./src/components/mcp/InterviewTalkDialog.vue')['default']
    MarqueeBar: typeof import('./src/components/MarqueeBar.vue')['default']
    PixelIcon: typeof import('./src/components/PixelIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareCardDialog: typeof import('./src/components/ShareCardDialog.vue')['default']
    SidebarMenu: typeof import('./src/components/chat/SidebarMenu.vue')['default']
    SkillGapDialog: typeof import('./src/components/mcp/SkillGapDialog.vue')['default']
    ThinkingSteps: typeof import('./src/components/chat/ThinkingSteps.vue')['default']
    VipBenefitsDialog: typeof import('./src/components/VipBenefitsDialog.vue')['default']
    WeatherPanel: typeof import('./src/components/WeatherPanel.vue')['default']
  }
}
